#lang racket

;;   ____      _                
;;  / ___|___ | | ___  _ __ ___ 
;; | |   / _ \| |/ _ \| '__/ __|
;; | |__| (_) | | (_) | |  \__ \
;;  \____\___/|_|\___/|_|  |___/

;; We have specified a predefined list of colors.

(provide colors)
(provide is-color?)

(define (is-color? c)
  (let ((valid? (assoc c colors)))
    (if valid?
        (cdr valid?)
        valid?)))
    

(define colors (list             
                (cons  '#:aliceblue            (list #xF0 #xF8 #xFF))
                (cons  '#:antiquewhite         (list #xFA #xEB #xD7))
                (cons  '#:aqua                 (list #x00 #xFF #xFF))
                (cons  '#:aquamarine           (list #x7F #xFF #xD4))
                (cons  '#:azure                (list #xF0 #xFF #xFF))
                (cons  '#:beige                (list #xF5 #xF5 #xDC))
                (cons  '#:bisque               (list #xFF #xE4 #xC4))
                (cons  '#:black                (list #x00 #x00 #x00))
                (cons  '#:blanchedalmond       (list #xFF #xEB #xCD))
                (cons  '#:blue                 (list #x00 #x00 #xFF))
                (cons  '#:blueviolet           (list #x8A #x2B #xE2))
                (cons  '#:brown                (list #xA5 #x2A #x2A))
                (cons  '#:burlywood            (list #xDE #xB8 #x87))
                (cons  '#:cadetblue            (list #x5F #x9E #xA0))
                (cons  '#:chartreuse           (list #x7F #xFF #x00))
                (cons  '#:chocolate            (list #xD2 #x69 #x1E))
                (cons  '#:coral                (list #xFF #x7F #x50))
                (cons  '#:cornflowerblue       (list #x64 #x95 #xED))
                (cons  '#:cornsilk             (list #xFF #xF8 #xDC))
                (cons  '#:crimson              (list #xDC #x14 #x3C))
                (cons  '#:cyan                 (list #x00 #xFF #xFF))
                (cons  '#:darkblue             (list #x00 #x00 #x8B))
                (cons  '#:darkcyan             (list #x00 #x8B #x8B))
                (cons  '#:darkgoldenrod        (list #xB8 #x86 #x0B))
                (cons  '#:darkgray             (list #xA9 #xA9 #xA9))
                (cons  '#:darkgreen            (list #x00 #x64 #x00))
                (cons  '#:darkkhaki            (list #xBD #xB7 #x6B))
                (cons  '#:darkmagenta          (list #x8B #x00 #x8B))
                (cons  '#:darkolivegreen       (list #x55 #x6B #x2F))
                (cons  '#:darkorange           (list #xFF #x8C #x00))
                (cons  '#:darkorchid           (list #x99 #x32 #xCC))
                (cons  '#:darkred              (list #x8B #x00 #x00))
                (cons  '#:darksalmon           (list #xE9 #x96 #x7A))
                (cons  '#:darkseagreen         (list #x8F #xBC #x8F))
                (cons  '#:darkslateblue        (list #x48 #x3D #x8B))
                (cons  '#:darkslategray        (list #x2F #x4F #x4F))
                (cons  '#:darkturquoise        (list #x00 #xCE #xD1))
                (cons  '#:darkviolet           (list #x94 #x00 #xD3))
                (cons  '#:deeppink             (list #xFF #x14 #x93))
                (cons  '#:deepskyblue          (list #x00 #xBF #xFF))
                (cons  '#:dimgray              (list #x69 #x69 #x69))
                (cons  '#:dodgerblue           (list #x1E #x90 #xFF))
                (cons  '#:firebrick            (list #xB2 #x22 #x22))
                (cons  '#:floralwhite          (list #xFF #xFA #xF0))
                (cons  '#:forestgreen          (list #x22 #x8B #x22))
                (cons  '#:fuchsia              (list #xFF #x00 #xFF))
                (cons  '#:gainsboro            (list #xDC #xDC #xDC))
                (cons  '#:ghostwhite           (list #xF8 #xF8 #xFF))
                (cons  '#:gold                 (list #xFF #xD7 #x00))
                (cons  '#:goldenrod            (list #xDA #xA5 #x20))
                (cons  '#:gray                 (list #x80 #x80 #x80))
                (cons  '#:green                (list #x00 #x80 #x00))
                (cons  '#:greenyellow          (list #xAD #xFF #x2F))
                (cons  '#:honeydew             (list #xF0 #xFF #xF0))
                (cons  '#:hotpink              (list #xFF #x69 #xB4))
                (cons  '#:indianred            (list #xCD #x5C #x5C))
                (cons  '#:indigo               (list #x4B #x00 #x82))
                (cons  '#:ivory                (list #xFF #xFF #xF0))
                (cons  '#:khaki                (list #xF0 #xE6 #x8C))
                (cons  '#:lavender             (list #xE6 #xE6 #xFA))
                (cons  '#:lavenderblush        (list #xFF #xF0 #xF5))
                (cons  '#:lawngreen            (list #x7C #xFC #x00))
                (cons  '#:lemonchiffon         (list #xFF #xFA #xCD))
                (cons  '#:lightblue            (list #xAD #xD8 #xE6))
                (cons  '#:lightcoral           (list #xF0 #x80 #x80))
                (cons  '#:lightcyan            (list #xE0 #xFF #xFF))
                (cons  '#:lightgoldenrodyellow (list #xFA #xFA #xD2))
                (cons  '#:lightgreen           (list #x90 #xEE #x90))
                (cons  '#:lightgrey            (list #xD3 #xD3 #xD3))
                (cons  '#:lightpink            (list #xFF #xB6 #xC1))
                (cons  '#:lightsalmon          (list #xFF #xA0 #x7A))
                (cons  '#:lightseagreen        (list #x20 #xB2 #xAA))
                (cons  '#:lightskyblue         (list #x87 #xCE #xFA))
                (cons  '#:lightslategray       (list #x77 #x88 #x99))
                (cons  '#:lightsteelblue       (list #xB0 #xC4 #xDE))
                (cons  '#:lightyellow          (list #xFF #xFF #xE0))
                (cons  '#:lime                 (list #x00 #xFF #x00))
                (cons  '#:limegreen            (list #x32 #xCD #x32))
                (cons  '#:linen                (list #xFA #xF0 #xE6))
                (cons  '#:magenta              (list #xFF #x00 #xFF))
                (cons  '#:maroon               (list #x80 #x00 #x00))
                (cons  '#:mediumaquamarine     (list #x66 #xCD #xAA))
                (cons  '#:mediumblue           (list #x00 #x00 #xCD))
                (cons  '#:mediumorchid         (list #xBA #x55 #xD3))
                (cons  '#:mediumpurple         (list #x93 #x70 #xDB))
                (cons  '#:mediumseagreen       (list #x3C #xB3 #x71))
                (cons  '#:mediumslateblue      (list #x7B #x68 #xEE))
                (cons  '#:mediumspringgreen    (list #x00 #xFA #x9A))
                (cons  '#:mediumturquoise      (list #x48 #xD1 #xCC))
                (cons  '#:mediumvioletred      (list #xC7 #x15 #x85))
                (cons  '#:midnightblue         (list #x19 #x19 #x70))
                (cons  '#:mintcream            (list #xF5 #xFF #xFA))
                (cons  '#:mistyrose            (list #xFF #xE4 #xE1))
                (cons  '#:moccasin             (list #xFF #xE4 #xB5))
                (cons  '#:navajowhite          (list #xFF #xDE #xAD))
                (cons  '#:navy                 (list #x00 #x00 #x80))
                (cons  '#:oldlace              (list #xFD #xF5 #xE6))
                (cons  '#:olive                (list #x80 #x80 #x00))
                (cons  '#:olivedrab            (list #x6B #x8E #x23))
                (cons  '#:orange               (list #xFF #xA5 #x00))
                (cons  '#:orangered            (list #xFF #x45 #x00))
                (cons  '#:orchid               (list #xDA #x70 #xD6))
                (cons  '#:palegoldenrod        (list #xEE #xE8 #xAA))
                (cons  '#:palegreen            (list #x98 #xFB #x98))
                (cons  '#:paleturquoise        (list #xAF #xEE #xEE))
                (cons  '#:palevioletred        (list #xDB #x70 #x93))
                (cons  '#:papayawhip           (list #xFF #xEF #xD5))
                (cons  '#:peachpuff            (list #xFF #xDA #xB9))
                (cons  '#:peru                 (list #xCD #x85 #x3F))
                (cons  '#:pink                 (list #xFF #xC0 #xCB))
                (cons  '#:plum                 (list #xDD #xA0 #xDD))
                (cons  '#:powderblue           (list #xB0 #xE0 #xE6))
                (cons  '#:purple               (list #x80 #x00 #x80))
                (cons  '#:rebeccapurple        (list #x66 #x33 #x99))
                (cons  '#:red                  (list #xFF #x00 #x00))
                (cons  '#:rosybrown            (list #xBC #x8F #x8F))
                (cons  '#:royalblue            (list #x41 #x69 #xE1))
                (cons  '#:saddlebrown          (list #x8B #x45 #x13))
                (cons  '#:salmon               (list #xFA #x80 #x72))
                (cons  '#:sandybrown           (list #xF4 #xA4 #x60))
                (cons  '#:seagreen             (list #x2E #x8B #x57))
                (cons  '#:seashell             (list #xFF #xF5 #xEE))
                (cons  '#:sienna               (list #xA0 #x52 #x2D))
                (cons  '#:silver               (list #xC0 #xC0 #xC0))
                (cons  '#:skyblue              (list #x87 #xCE #xEB))
                (cons  '#:slateblue            (list #x6A #x5A #xCD))
                (cons  '#:slategray            (list #x70 #x80 #x90))
                (cons  '#:snow                 (list #xFF #xFA #xFA))
                (cons  '#:springgreen          (list #x00 #xFF #x7F))
                (cons  '#:steelblue            (list #x46 #x82 #xB4))
                (cons  '#:tan                  (list #xD2 #xB4 #x8C))
                (cons  '#:teal                 (list #x00 #x80 #x80))
                (cons  '#:thistle              (list #xD8 #xBF #xD8))
                (cons  '#:tomato               (list #xFF #x63 #x47))
                (cons  '#:turquoise            (list #x40 #xE0 #xD0))
                (cons  '#:violet               (list #xEE #x82 #xEE))
                (cons  '#:wheat                (list #xF5 #xDE #xB3))
                (cons  '#:white                (list #xFF #xFF #xFF))
                (cons  '#:whitesmoke           (list #xF5 #xF5 #xF5))
                (cons  '#:yellow               (list #xFF #xFF #x00))
                (cons  '#:yellowgreen          (list #x9A #xCD #x32))))
